### ISSUE TITLE
"Failed to execute the [include] macro. Cause: [Current user [null] doesn't have view rights on document "

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-googleapps#27] opened 2019-09-04 17:54 UTC
After installing the Google Apps Integration (Pro) and logging out of XWiki an error appears
"Failed to execute the [include] macro. Cause: [Current user [null] doesn't have view rights on document [Document xwiki:Licenses.Code.VelocityMacros]]. Click on this message for details."

Environment: Cloud - XWiki 10.11.9 with Chrome 76

![Error1](https://user-images.githubusercontent.com/40691112/64278720-12bca200-cf56-11e9-8cc5-746b8cf53bb3.jpg)
[FullError.txt](https://github.com/xwikisas/application-googleapps/files/3575851/FullError.txt)

**Comment by mflorea** [comment] 2019-09-05 14:13
I assume this error message is visible every time you login with Google so it needs to be fixed ASAP.

**Comment by mflorea** [comment] 2019-09-06 09:57
It seems this is not related to Google Apps. The problem is most probably caused by this include https://github.com/xwikisas/application-licensing/commit/277b559dd21e8ecb4028e879801c96dca79be2a1#diff-4cf6297a2a582a0d20ef00bfde4da20cR214 in the latest version of the Licensor. @acotiuga please look at this ASAP. Thanks.

**Comment by acotiuga** [comment] 2019-09-06 10:52
This issue is duplicate of https://github.com/xwikisas/application-licensing/issues/71.

**Closed by acotiuga** 2019-09-06 10:52 UTC
Labels: Priority: Critical, Type: Bug

**Comment by polx** [comment] 2019-09-06 11:06
Thank you Alex, so it means that you're going into a release cycle, right?
@ane-gabriela : Do I mistake, or this warning has "just" bothered the view and otherwise not bothered the use of the google apps application?
paul

**Comment by acotiuga** [comment] 2019-09-06 11:07
I'm doing some more testing. I will handle the needed releases today.
