### ISSUE TITLE
Uninstalling GoogleApps gives many missing programming rights errors in the console

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-googleapps#17] opened 2019-04-08 12:38 UTC
Steps to reproduce:

1. On 8.4 and/or 10.8.3 have the app installed - in this case the licence was expired
2. As Admin uninstall the app
3. Observe the information from the Console
4. Close the wiki
5. Open and access the wiki again
6. Observe the information from the Console

Expected results: The app in uninstalled.

Actual results: The app is uninstalled but many programming rights errors appear in the Console. Also, in Administration > Other, googleapps remain with "googleapps.config.heading". Each time the wiki is closed and open/acceded again the errors appear in the console. 

Environment: Windows 10, XWiki 8.4 and 10.8.3 Standard with Chrome 73 and Edge 18

[ConsoleAccesing8.4AfterUninstall.txt](https://github.com/xwikisas/application-googleapps/files/3054263/ConsoleAccesing8.4AfterUninstall.txt)

[ConsoleAccesing10.8.3AfterUninstall.txt](https://github.com/xwikisas/application-googleapps/files/3054264/ConsoleAccesing10.8.3AfterUninstall.txt)

![Accesing10 8 3AfterUninstallingGoogleIntPRO](https://user-images.githubusercontent.com/40691112/55724471-25b55f80-5a14-11e9-844f-a4dbf00d4360.jpg)

![8 4](https://user-images.githubusercontent.com/40691112/55724473-264df600-5a14-11e9-9c53-893dbe4fc91e.jpg)

![UninstallingGoogleIntPRO](https://user-images.githubusercontent.com/40691112/55724474-264df600-5a14-11e9-998b-06f14a372c7c.jpg)

**Comment by ilieandriuta** [comment] 2022-01-14 13:19
I got these errors also when installing the application (Google Apps Pro 2.5.1 on XWiki 13.10.2, PostgreSQL 14, Tomcat 9.0.56, Docker).

**Comment by polx** [comment] 2022-01-14 13:28
Well, isn't it "simply" because the configurations in xwiki.cfg are still there?
Uninstalling includes undoing the installation steps.

**Comment by mflorea** [comment] 2022-01-17 05:49
@ilieandriuta can you please be more precise: at **which step** of the [documented installation process](https://store.xwiki.com/xwiki/bin/view/Extension/GoogleAppsIntegration#installation) are you getting the errors? And **which errors** are you referring to: the one in the server logs about ``xwiki:GoogleApps:AuthService`` missing programming rights or the one about the administration section or both?

> As Admin uninstall the app

@ane-gabriela did you undo all the [documented installation steps](https://store.xwiki.com/xwiki/bin/view/Extension/GoogleAppsIntegration#installation)? Also, were all checkboxes checked when the Extension Manager asked you to confirm the deletion of the Google Apps pages?

> Also, in Administration > Other, googleapps remain with "googleapps.config.heading".

In your screenshot you show the content of the section but the menu entry is not visible. Is the Google Apps menu entry still present after uninstalling the application with the Extension Manager, even after reloading the page? Even after restarting the wiki?

I just tested with a clean XWiki 13.10.2 by installing and uninstalling the Google Apps using just the Extension Manager (no license generated and no configuration change) and I didn't see any error in the logs and the administration menu disappeared after uninstall.

**Comment by AndreeaChi** [comment] 2022-01-17 14:59
I did not reproduce any issues at install or uninstall.

I did the following steps:
1. Followed the documentation here in terms of the required configuration on the Google Console side and the XWiki side (the lines to add in the xwiki.cfg file of the local Jetty 13.10.2)
2. Started the local Jetty 13.10.2 on Chrome
3. Installed the Google Apps Integration 2.5.1 and added a trial license.
4. Added the client ID, secret on the Google Apps configuration page and the domain set in the project.
5. Logged in successfully with a Google account on both Chrome incognito and FIrefox
6. Then, I went back on the Google browser where I was still logged in with Admin, on the wiki administration, Extensions.
7. Searched for Google Apps Integration and Uninstalled it. Made sure to select all pages shown
![image](https://user-images.githubusercontent.com/36840106/149792613-c54e5a67-389a-4302-a3d0-c9d215720daf.png)
8. Uninstall was complete, no related logs in the Console.

**Comment by polx** [comment] 2022-01-17 15:01
@AndreeaChi : you need to restart now.

**Comment by AndreeaChi** [comment] 2022-01-17 15:06
I was about to write that now, that the next step done was to Install again the app and in the console I noticed:
![image](https://user-images.githubusercontent.com/36840106/149793764-82fa6f8a-2404-45b5-8ea7-13db23e082e7.png)
I did not restart the server before installing the app again.

**Comment by polx** [comment] 2022-01-17 15:30
This is because of the line in xwiki.cfg

**Comment by AndreeaChi** [comment] 2022-01-17 15:33
I confirm as well that it's because of adding the Google Authentication lines in the xwiki.cfg file described at this step in the documentation:

Activate the Google Authentication
In order to activate the Groovy Authentication, you need to update the following settings in the xwiki.cfg file (webapps > xwiki > WEB-INF) and restart the wiki:

xwiki.authentication.authclass=com.xpn.xwiki.user.impl.xwiki.GroovyAuthServiceImpl
xwiki.authentication.groovy.pagename=xwiki:GoogleApps.AuthService

I did a quick test of adding the lines, restart, removing the lines, restart, and then adding the lines again to see if they reappear, and they did show up again in the console.

**Comment by mflorea** [comment] 2022-01-18 09:06
Closing as invalid because the issue doesn't reproduce if you undo **all** the installation steps.

**Closed by mflorea** 2022-01-18 09:06 UTC
Labels: Priority: Critical, Type: Bug, Status: Invalid

**Comment by ilieandriuta** [comment] 2022-01-19 13:09
I was referring to errors from the server logs about xwiki:GoogleApps:AuthService missing programming rights, but indeed, it seems they are related to the lines that need to be added in xwiki.cfg. 
I've re-tested on XWiki 13.10.2 and if these lines are added in xwiki.cfg after the application is installed and then (in reverse) if they are removed before the application is uninstalled, no errors are displayed in console.
